#!/usr/bin/env python3
"""Export the persisted LightRAG entity graph as a separate Obsidian vault."""

from __future__ import annotations

import argparse
from collections import Counter
from datetime import datetime, timezone
import hashlib
import json
import math
from pathlib import Path
import re
import shutil
from typing import Any

import networkx as nx


GENERATED_MARKER = ".lightrag-obsidian-generated"
INVALID_FILENAME = re.compile(r'[*"\\/<>:|?#^\[\]]')


def _safe_component(label: str, *, limit: int = 110) -> str:
    value = INVALID_FILENAME.sub("_", label).strip().strip(".")
    value = re.sub(r"\s+", " ", value) or "unnamed"
    return value[:limit].rstrip()


def _note_name(node_id: str) -> str:
    digest = hashlib.sha1(node_id.encode("utf-8")).hexdigest()[:10]
    return f"{_safe_component(node_id)}--{digest}.md"


def _yaml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _display(value: Any) -> str:
    return str(value or "").strip()


def _tag_component(value: str) -> str:
    normalized = re.sub(r"[^a-z0-9_-]+", "-", value.lower()).strip("-")
    return normalized or "unknown"


def _wikilink(node_id: str, filenames: dict[str, str]) -> str:
    path = f"entities/{filenames[node_id][:-3]}"
    # Obsidian uses pipes/brackets as wikilink delimiters. Keep the entity ID
    # intact in frontmatter/title, but make its display alias parser-safe.
    alias = node_id.replace("|", "¦").replace("[", "(").replace("]", ")")
    return f"[[{path}|{alias}]]"


def _prepare_output(output_dir: Path) -> None:
    if output_dir.exists():
        marker = output_dir / GENERATED_MARKER
        if not marker.exists():
            raise RuntimeError(
                f"refusing_to_replace_non_generated_vault:{output_dir}"
            )
        shutil.rmtree(output_dir)
    (output_dir / "entities").mkdir(parents=True)
    (output_dir / "types").mkdir()
    (output_dir / ".obsidian").mkdir()
    (output_dir / GENERATED_MARKER).write_text(
        "Generated by scripts/export_lightrag_obsidian.py\n",
        encoding="utf-8",
    )


def _write_entity_notes(
    graph: nx.Graph,
    output_dir: Path,
    filenames: dict[str, str],
) -> None:
    for node_id, attrs in graph.nodes(data=True):
        node_id = str(node_id)
        entity_type = _display(attrs.get("entity_type")) or "unknown"
        description = _display(attrs.get("description"))
        source_id = _display(attrs.get("source_id"))
        file_path = _display(attrs.get("file_path"))
        degree = int(graph.degree[node_id])

        lines = [
            "---",
            "lightrag_entity: true",
            f"entity_id: {_yaml_string(node_id)}",
            f"entity_type: {_yaml_string(entity_type)}",
            f"degree: {degree}",
            "tags:",
            "  - lightrag/entity",
            f"  - lightrag/type/{_tag_component(entity_type)}",
            "---",
            "",
            f"# {node_id}",
            "",
        ]
        if description:
            lines.extend([description, ""])

        lines.extend(["## Relationships", ""])
        relationships: list[tuple[str, str]] = []
        for neighbor in graph.neighbors(node_id):
            neighbor_id = str(neighbor)
            edge = graph.get_edge_data(node_id, neighbor) or {}
            edge_description = _display(edge.get("description"))
            keywords = _display(edge.get("keywords"))
            detail = edge_description
            if keywords:
                detail = f"{detail} _Keywords: {keywords}_" if detail else f"_Keywords: {keywords}_"
            relationships.append(
                (
                    neighbor_id.casefold(),
                    f"- {_wikilink(neighbor_id, filenames)}"
                    + (f" — {detail}" if detail else ""),
                )
            )
        if relationships:
            lines.extend(item for _, item in sorted(relationships))
        else:
            lines.append("_No graph relationships._")

        lines.extend(["", "## Provenance", ""])
        lines.append(f"- Source file(s): `{file_path}`" if file_path else "- Source file(s): unknown")
        lines.append(f"- Source chunk(s): `{source_id}`" if source_id else "- Source chunk(s): unknown")
        lines.append(f"- Graph degree: {degree}")
        lines.append("")

        note_path = output_dir / "entities" / filenames[node_id]
        note_path.write_text("\n".join(lines), encoding="utf-8")


def _write_type_indexes(
    graph: nx.Graph,
    output_dir: Path,
    filenames: dict[str, str],
) -> dict[str, int]:
    by_type: dict[str, list[str]] = {}
    for node_id, attrs in graph.nodes(data=True):
        entity_type = _display(attrs.get("entity_type")) or "unknown"
        by_type.setdefault(entity_type, []).append(str(node_id))

    counts: dict[str, int] = {}
    for entity_type, node_ids in sorted(by_type.items(), key=lambda item: item[0].casefold()):
        counts[entity_type] = len(node_ids)
        lines = [
            "---",
            "tags:",
            "  - lightrag/moc",
            f"  - lightrag/type/{_tag_component(entity_type)}",
            "---",
            "",
            f"# Entity type: {entity_type}",
            "",
            f"Total: **{len(node_ids):,}**",
            "",
        ]
        for node_id in sorted(node_ids, key=str.casefold):
            lines.append(f"- {_wikilink(node_id, filenames)}")
        filename = f"{_safe_component(entity_type)}.md"
        (output_dir / "types" / filename).write_text("\n".join(lines) + "\n", encoding="utf-8")
    return counts


def _write_home(
    graph: nx.Graph,
    output_dir: Path,
    filenames: dict[str, str],
    type_counts: dict[str, int],
    source_graph: Path,
) -> None:
    degree = sorted(graph.degree, key=lambda item: (-item[1], str(item[0]).casefold()))
    component_count = nx.number_connected_components(graph)
    largest_component = max((len(c) for c in nx.connected_components(graph)), default=0)
    isolates = nx.number_of_isolates(graph)
    generated_at = datetime.now(timezone.utc).isoformat()

    lines = [
        "# LightRAG Knowledge Graph",
        "",
        "Vault này là bản export chỉ-đọc của graph tài liệu LightRAG, tách biệt với vault source code Graphify.",
        "",
        "## Snapshot",
        "",
        f"- Generated: `{generated_at}`",
        f"- Source: `{source_graph}`",
        f"- Entities: **{graph.number_of_nodes():,}**",
        f"- Relationships: **{graph.number_of_edges():,}**",
        f"- Connected components: **{component_count:,}**",
        f"- Largest component: **{largest_component:,} entities**",
        f"- Isolated entities: **{isolates:,}**",
        "",
        "## Entity types",
        "",
    ]
    for entity_type, count in sorted(type_counts.items(), key=lambda item: (-item[1], item[0])):
        type_note = _safe_component(entity_type)
        lines.append(f"- [[types/{type_note}|{entity_type}]]: {count:,}")

    lines.extend(["", "## Top graph hubs", ""])
    for node_id, node_degree in degree[:100]:
        lines.append(f"- {_wikilink(str(node_id), filenames)} — degree {node_degree}")

    lines.extend(
        [
            "",
            "## How to explore",
            "",
            "1. Mở `graph.canvas` để xem các hub lớn.",
            "2. Mở Graph view của Obsidian để duyệt toàn bộ wikilink.",
            "3. Lọc bằng tag `#lightrag/type/...` hoặc mở các MOC trong `types/`.",
            "",
            "> Đây là snapshot generated. Re-export sẽ thay toàn bộ vault này.",
            "",
        ]
    )
    (output_dir / "LightRAG Graph Home.md").write_text("\n".join(lines), encoding="utf-8")


def _write_canvas(
    graph: nx.Graph,
    output_dir: Path,
    filenames: dict[str, str],
    *,
    hub_count: int = 60,
) -> None:
    hubs = [
        str(node_id)
        for node_id, _ in sorted(
            graph.degree,
            key=lambda item: (-item[1], str(item[0]).casefold()),
        )[:hub_count]
    ]
    hub_set = set(hubs)
    canvas_nodes = []
    radius = max(900.0, hub_count * 18.0)
    for index, node_id in enumerate(hubs):
        angle = (2 * math.pi * index) / max(1, len(hubs))
        canvas_nodes.append(
            {
                "id": f"n{index}",
                "type": "file",
                "file": f"entities/{filenames[node_id]}",
                "x": round(math.cos(angle) * radius),
                "y": round(math.sin(angle) * radius),
                "width": 320,
                "height": 180,
            }
        )
    canvas_id = {node_id: f"n{index}" for index, node_id in enumerate(hubs)}
    canvas_edges = []
    edge_index = 0
    for source, target in graph.edges:
        source_id, target_id = str(source), str(target)
        if source_id not in hub_set or target_id not in hub_set:
            continue
        canvas_edges.append(
            {
                "id": f"e{edge_index}",
                "fromNode": canvas_id[source_id],
                "fromSide": "right",
                "toNode": canvas_id[target_id],
                "toSide": "left",
            }
        )
        edge_index += 1
    (output_dir / "graph.canvas").write_text(
        json.dumps({"nodes": canvas_nodes, "edges": canvas_edges}, ensure_ascii=False),
        encoding="utf-8",
    )


def _write_obsidian_settings(output_dir: Path) -> None:
    graph_settings = {
        "collapse-filter": False,
        "search": "",
        "showTags": True,
        "showAttachments": False,
        "hideUnresolved": True,
        "showOrphans": True,
        "collapse-color-groups": False,
        "colorGroups": [
            {"query": "tag:#lightrag/type/method", "color": {"a": 1, "rgb": 39423}},
            {"query": "tag:#lightrag/type/data", "color": {"a": 1, "rgb": 16753920}},
            {"query": "tag:#lightrag/type/person", "color": {"a": 1, "rgb": 16734003}},
            {"query": "tag:#lightrag/type/concept", "color": {"a": 1, "rgb": 10040012}},
        ],
        "collapse-display": False,
        "showArrow": False,
        "textFadeMultiplier": 0,
        "nodeSizeMultiplier": 1,
        "lineSizeMultiplier": 1,
        "collapse-forces": False,
        "centerStrength": 0.518713248970312,
        "repelStrength": 10,
        "linkStrength": 1,
        "linkDistance": 250,
        "scale": 0.3,
        "close": False,
    }
    (output_dir / ".obsidian" / "graph.json").write_text(
        json.dumps(graph_settings, indent=2),
        encoding="utf-8",
    )
    (output_dir / ".obsidian" / "app.json").write_text(
        json.dumps({"showLineNumber": False, "newFileLocation": "current"}, indent=2),
        encoding="utf-8",
    )


def export(source_graph: Path, output_dir: Path) -> None:
    graph = nx.read_graphml(source_graph)
    if graph.is_directed():
        graph = graph.to_undirected()
    graph = nx.Graph(graph)
    filenames = {str(node_id): _note_name(str(node_id)) for node_id in graph.nodes}

    _prepare_output(output_dir)
    _write_entity_notes(graph, output_dir, filenames)
    type_counts = _write_type_indexes(graph, output_dir, filenames)
    _write_home(graph, output_dir, filenames, type_counts, source_graph.resolve())
    _write_canvas(graph, output_dir, filenames)
    _write_obsidian_settings(output_dir)

    manifest = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source_graph": str(source_graph.resolve()),
        "nodes": graph.number_of_nodes(),
        "edges": graph.number_of_edges(),
        "components": nx.number_connected_components(graph),
        "entity_types": Counter(
            _display(attrs.get("entity_type")) or "unknown"
            for _, attrs in graph.nodes(data=True)
        ),
    }
    (output_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    print(
        f"Exported {graph.number_of_nodes()} entities and "
        f"{graph.number_of_edges()} relationships to {output_dir}"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source",
        type=Path,
        default=Path("data/lightrag/graph_chunk_entity_relation.graphml"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("obsidian-lightrag-vault"),
    )
    args = parser.parse_args()
    export(args.source, args.output)


if __name__ == "__main__":
    main()
